services:
  app:
    image: goormdotcom-user-service:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: user-service
    ports:
      - 8081:8081
    environment:
      - SPRING_PROFILES_ACTIVE=dev,secret
    volumes:
      - ./config:/app/config
    user: 1000:1000
