name: order-service dev-branch CI workflow

on:
  pull_request:
    branches: [ "dev" ]

jobs:

  # 테스트
  test:
    env:
      SPRING_PROFILES_ACTIVE: test
      JWT_SECRET: ${{ secrets.JWT_SECRET }}

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Build with Gradle Wrapper
        run: ./gradlew test

  # 테스트 실패시 결과 업로드
  upload-report-to-s3-on-build-failure:
    name: Upload a reports to s3 on build failure
    needs:
      - test
    runs-on: ubuntu-latest
    if: failure()
    steps:
      # GitHub ACCESS KEY and SECRET KEY로 자격증명
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      # s3에 테스트 결과 업로드
      - name: Upload test report to S3
        run: |
          RUN_ID=${GITHUB_RUN_ID}
          aws s3 sync build/reports/tests/test \
            s3://${{ secrets.S3_REPORT_BUCKET }}/reports/${RUN_ID}/ \
            --delete

  # 테스트 실패 시
  notify-slack-on-build-failure:
    name: Notify Slack on build failure
    needs:
      - test
    runs-on: ubuntu-latest
    if: failure()                        # 실패했을 때만 실행
    steps:
      - name: Send Slack message on failure
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          CF_DOMAIN: ${{ secrets.CF_REPORT_DOMAIN }} # 예: ci.goormdotcom.com
        run: |
          REPO="${GITHUB_REPOSITORY}"
          BRANCH_FROM="${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}"   # PR일 경우: from 브랜치
          BRANCH_TO="${GITHUB_BASE_REF:-main}"                   # PR일 경우: target 브랜치
          RUN_ID="${GITHUB_RUN_ID}"
          GH_URL="https://github.com/${REPO}/actions/runs/${RUN_ID}"
          REPORT_URL="https://${CF_DOMAIN}/reports/${RUN_ID}/index.html"

          MESSAGE=$(cat <<EOF
            ❌ *Build/Test Failed*
        
            *Repository* : \`${REPO}\`
            *Branch* : \`${BRANCH_FROM}\` → \`${BRANCH_TO}\`
        
            *GitHub Run*: <${GH_URL}|View in GitHub>
            *Report* : <${REPORT_URL}|View HTML Report>
            EOF
            )
            
            payload=$(jq -n --arg text "$MESSAGE" '{ text: $text }')
            curl -X POST -H 'Content-type: application/json' \
            --data "$payload" \
            "$SLACK_WEBHOOK_URL"
